"""Shared SQL emitter for the bidmonkey content importers.

Both db/import_problems.py (one book's copy-pasted text) and db/normalize_quiz.py
(hand-authored YAML) reduce their input to the same row shapes and hand them here
to get idempotent upsert SQL for sources / quizzes / problems / quizzes_problems:

    print(emit_sql(sources, quizzes, problems, links), end="")

Every insert is `on conflict … do update`, so fixing the source and re-running
just updates the rows (better for DB-authored content than plain inserts). Rows
are plain dicts:

    sources:  {slug, title}
    quizzes:  {slug, title, source}
    problems: {slug, title, source, difficulty, tags, hero, dealer,
               vulnerability, deal, auction, play, contract, commentary}
    links:    {quiz_slug, problem_slug, ordinal}

Missing keys default to NULL (or [] for tags / auction). Stdlib only, so it runs
under plain `python3` and `uv run` alike.
"""
import json

PROBLEM_COLS = ["slug", "title", "source", "difficulty", "tags", "hero", "dealer",
                "vulnerability", "deal", "auction", "play", "contract", "commentary"]


def sql_str(v):
    return "NULL" if v is None else "'" + str(v).replace("'", "''") + "'"


def sql_json(v):
    return "NULL" if v is None else sql_str(json.dumps(v, ensure_ascii=False)) + "::jsonb"


def sql_text_array(xs):
    return "ARRAY[" + ", ".join(sql_str(x) for x in (xs or [])) + "]::text[]"


def sql_int(v):
    return "NULL" if v is None else str(int(v))


def _problem_value(p, col):
    v = p.get(col)
    if col == "tags":
        return sql_text_array(v)
    if col == "difficulty":
        return sql_int(v)
    if col == "auction":                       # NOT NULL default '[]' — never emit NULL
        return sql_json([] if v is None else v)
    if col in ("deal", "play"):
        return sql_json(v)
    return sql_str(v)


def emit_sql(sources, quizzes, problems, links):
    out = ["-- Generated by the bidmonkey importer — do not edit by hand.", "begin;"]

    out.append("\n-- sources")
    for s in sources:
        out.append(
            f"insert into sources (slug, title) values ({sql_str(s['slug'])}, {sql_str(s['title'])})\n"
            f"  on conflict (slug) do update set title = excluded.title;")

    out.append("\n-- quizzes")
    for q in quizzes:
        out.append(
            f"insert into quizzes (slug, title, source) values "
            f"({sql_str(q['slug'])}, {sql_str(q['title'])}, {sql_str(q['source'])})\n"
            f"  on conflict (slug) do update set title = excluded.title, source = excluded.source;")

    out.append("\n-- problems")
    upd = ", ".join(f"{c} = excluded.{c}" for c in PROBLEM_COLS if c != "slug")
    for p in problems:
        vals = ", ".join(_problem_value(p, c) for c in PROBLEM_COLS)
        out.append(
            f"insert into problems ({', '.join(PROBLEM_COLS)})\nvalues ({vals})\n"
            f"  on conflict (slug) do update set {upd}, updated_at = now();")

    out.append("\n-- quizzes_problems (ordinal = 1-based position within the quiz)")
    for lk in links:
        out.append(
            f"insert into quizzes_problems (quiz_slug, problem_slug, ordinal) values "
            f"({sql_str(lk['quiz_slug'])}, {sql_str(lk['problem_slug'])}, {int(lk['ordinal'])})\n"
            f"  on conflict (quiz_slug, problem_slug) do update set ordinal = excluded.ordinal;")

    out.append("commit;")
    return "\n".join(out) + "\n"
