// Generate supabase/seed.sql from the frontend sample data. This seeds the
// *existing* problems; `supabase db reset` runs it after the migrations. After
// the initial load, new problems are authored directly in the DB (insert via
// `npm run psql`), and regenerating this would only reproduce the samples.
//
//   node db/gen-seed.mjs > supabase/seed.sql
//
// Runs on Node's built-in TypeScript stripping — the data modules are plain
// object literals with type-only imports, so no build step is needed.

import { problems } from '../web/src/data/problems.ts'
import { sources, quizzes } from '../web/src/data/catalog.ts'

// SQL literal for a string, or NULL. Doubles single quotes (Postgres escaping).
const s = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
// jsonb literal (NULL passes through).
const j = (v) => (v == null ? 'NULL' : `${s(JSON.stringify(v))}::jsonb`)
// text[] literal from a list of strings.
const arr = (xs) => (xs?.length ? `ARRAY[${xs.map(s).join(', ')}]::text[]` : `ARRAY[]::text[]`)
const n = (v) => (v == null ? 'NULL' : String(v))

const lines = []
lines.push('-- Generated by db/gen-seed.mjs — do not edit by hand.')
lines.push('-- Loaded by `supabase db reset` after the migrations.')
lines.push('begin;')

lines.push('\n-- sources')
for (const src of sources) {
  lines.push(`insert into sources (slug, title) values (${s(src.slug)}, ${s(src.title)});`)
}

lines.push('\n-- problems')
for (const p of problems) {
  lines.push(
    'insert into problems\n' +
      '  (id, title, source, difficulty, tags, hero, dealer, vulnerability, deal, auction, play, contract, commentary)\n' +
      `values (${n(p.id)}, ${s(p.title)}, ${s(p.source)}, ${n(p.difficulty)}, ${arr(p.tags)}, ` +
      `${s(p.hero)}, ${s(p.dealer)}, ${s(p.vulnerability)}, ${j(p.deal)}, ${j(p.auction ?? [])}, ` +
      `${j(p.play)}, ${s(p.contract)}, ${s(p.commentary)});`,
  )
}

lines.push('\n-- quizzes')
for (const q of quizzes) {
  lines.push(`insert into quizzes (slug, title, source) values (${s(q.slug)}, ${s(q.title)}, ${s(q.source)});`)
}

lines.push('\n-- quizzes_problems (ordinal = 1-based position within the quiz)')
for (const q of quizzes) {
  q.problemIds.forEach((pid, i) => {
    lines.push(
      `insert into quizzes_problems (quiz_slug, problem_id, ordinal) values (${s(q.slug)}, ${n(pid)}, ${n(i + 1)});`,
    )
  })
}

lines.push('\n-- Bump the identity sequence past the explicit ids just inserted.')
lines.push("select setval(pg_get_serial_sequence('problems', 'id'), (select max(id) from problems));")
lines.push('commit;')

process.stdout.write(lines.join('\n') + '\n')
