// Generate the SQLite seed from the frontend sample data, so the database and
// the app never drift. Writes SQL to stdout.
//
//   node db/gen-seed.mjs > seed.sql
//   node db/gen-seed.mjs | sqlite3 bidmonkey.db     (after schema.sql is loaded)
//
// Runs on Node's built-in TypeScript stripping — the data modules are plain
// object literals with type-only imports, so no build step is needed.

import { problems } from '../web/src/data/problems.ts'
import { sources, quizzes } from '../web/src/data/catalog.ts'

// SQL literal for a string, or NULL for null/undefined. Doubles single quotes.
const s = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
// SQL literal for a value stored as JSON text (NULL passes through).
const j = (v) => (v == null ? 'NULL' : s(JSON.stringify(v)))
const n = (v) => (v == null ? 'NULL' : String(v))

const lines = []
lines.push('-- Generated by db/gen-seed.mjs — do not edit by hand.')
lines.push('-- Rebuild: node db/gen-seed.mjs | sqlite3 bidmonkey.db')
lines.push('PRAGMA foreign_keys = ON;')
lines.push('BEGIN;')

lines.push('\n-- sources')
for (const src of sources) {
  lines.push(`INSERT INTO sources (slug, title) VALUES (${s(src.slug)}, ${s(src.title)});`)
}

lines.push('\n-- problems')
for (const p of problems) {
  lines.push(
    'INSERT INTO problems\n' +
      '  (id, title, source, difficulty, tags, hero, dealer, vulnerability, deal, auction, play, contract, commentary)\n' +
      `VALUES (${n(p.id)}, ${s(p.title)}, ${s(p.source)}, ${n(p.difficulty)}, ${j(p.tags ?? [])}, ` +
      `${s(p.hero)}, ${s(p.dealer)}, ${s(p.vulnerability)}, ${j(p.deal)}, ${j(p.auction ?? [])}, ` +
      `${j(p.play)}, ${s(p.contract)}, ${s(p.commentary)});`,
  )
}

lines.push('\n-- quizzes')
for (const q of quizzes) {
  lines.push(`INSERT INTO quizzes (slug, title, source) VALUES (${s(q.slug)}, ${s(q.title)}, ${s(q.source)});`)
}

lines.push('\n-- quizzes_problems (ordinal = 1-based position within the quiz)')
for (const q of quizzes) {
  q.problemIds.forEach((pid, i) => {
    lines.push(
      `INSERT INTO quizzes_problems (quiz_slug, problem_id, ordinal) VALUES (${s(q.slug)}, ${n(pid)}, ${n(i + 1)});`,
    )
  })
}

lines.push('COMMIT;')
process.stdout.write(lines.join('\n') + '\n')
